version: "3.9"

services:
  db:
    image: postgres:15
    container_name: taskmanager-db
    restart: always
    env_file:
      - .env.docker
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  api:
    build: .
    container_name: taskmanager-api
    restart: always
    depends_on:
      - db
    env_file:
      - .env.docker
    ports:
      - "8000:8000"
    networks:
      - backend
    command: >
      sh -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000"

  pgadmin:
    image: dpage/pgadmin4:7
    container_name: taskmanager-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    env_file:
      - .env.docker
    ports:
      - "5050:80"
    networks:
      - backend

volumes:
  postgres_data:

networks:
  backend:
